INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (1,'1@1','1','GENERAL','1','W','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (2,'2@1','2','GENERAL','1','W','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (3,'3@1','3','GENERAL','1','M','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (4,'4@1','4','GENERAL','1','M','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (5,'5@1','5','GENERAL','1','M','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (6,'6@1','6','PAUSE','1','M','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (7,'7@1','7','GENERAL','1','M','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (8,'8@1','8','SLEEP','1','M','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (9,'9@1','9','GENERAL','1','W','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (10,'10@1','10','SLEEP','1','W','940810',now());
INSERT INTO USER_INFO (USER_NO,USER_ID,USER_PW,USER_STATUS,USER_NAME,USER_GENDER,USER_BIRTH,LAST_CONNECTION) values (11,'11@1','11','GENERAL','1','W','940810',now());


INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (1,'111',1,5,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (2,'222',1,1,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (3,'333',2,5,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (4,'444',2,5,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (5,'555',2,1,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (6,'666',3,4,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (7,'777',3,3,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (8,'888',3,5,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (9,'999',3,5,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (10,'10',4,1,'리뷰',now(),0);
INSERT INTO BOOK_REVIEW (REVIEW_NO,ISBN,USER_NO,RATING,REVIEW_CONTENTS,CREATE_DATE,DECLARATION) values (11,'11',4,1,'리뷰',now(),0);

